spring.application.name=knowledge-decay
spring.datasource.url=jdbc:postgresql://localhost:5432/knowledge_decay
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8081

spring.main.allow-bean-definition-overriding=true
spring.security.enabled=false
